Incorporate working auth endpoints
bonsai-org/frontend pull request #18
Opened 2024-09-10 02:30 UTC by maahsnd

Calls to api on log in and sign up. Valid responses include username and profile photo. Stores these in an authContext, which is then accessed from the navBar to update userIcon. If no profile photo present (it's optional), render the first letter of username. If no username, render a smiley face (should find something better for our anonymous users later on but ok).

2024-09-10 03:51 UTC, DONTSTOPLOVINGMEBABY commented
will check out tomorrow good sir

2024-09-11 00:58 UTC, maahsnd commented
Added a login button that is displayed in the navbar if user is not logged in (instead of displaying the userIcon). Refactored userIcon to contain protected links. To that end, created a link for About docs in the navbar, and removed it from the user slide out menu.

2024-09-11 05:41 UTC, DONTSTOPLOVINGMEBABY requested changes
This PR is looking really good and is feeling complete. 

There is just one small error that I found in handleSignupSubmit, and I added a comment to it. After this, I think we are set to merge

2024-09-11 05:41 UTC, DONTSTOPLOVINGMEBABY commented on src/components/authForm/AuthForm.tsx
Add check for a 409 status code in the conditional in the handleSignupSubmit function. 

```typescript
// ... other conditionals
else if (response.status === HttpStatusCode.Conflict) {
  setError(
    'Username and or email unavailable.'
  )
// continue conditional checks
}
```

2024-09-11 15:34 UTC, maahsnd commented on src/components/authForm/AuthForm.tsx
Good catch. Added in.

2024-09-11 16:13 UTC, DONTSTOPLOVINGMEBABY approved these changes
sweet... see you in like 45 mins

2024-09-11 16:46 UTC, merged